:fire: :wrench: Remove/depreciated pkg_resource usage and other depreciated usage (#1384)
* Add Support for Graviton 2 / ARM Architecture

* Changed parameter in README to architecture

* Removed redundant blank line

* Bugfix + black compliance

* Fix: architecture argument not used properly

* Fixed black compliance

* Fixed architecture label for wheels, added check for invalid architecture

* Testing architecture

* Added tests for ARM64 architecture

* Only allow ARM64 arch if Python version >= 3.8

* Removed redundant references to architecture

* Removed redundant references to architecture

* Added test for default architecture setting

* added .pre-commit hook for black-check and isort-check

* Fixed test failure  in Python 3.7

* :wrench: re-work regex for abi3

* :wrench: fix Zappa.create_lambda_function to pass a list to 'Architectures' in `create_function()` call.

* :wrench: replace usage of os.listdir()/os.path.join() with pathlib.Path object usage.
:white_check_mark: update

* :whtie_check_mark: Update `test_copy_editable_packages` testcase for update to use Path objects

* :fire: remove unnecessary comments

* :wrench: replace (depreciated) click.BaseCommand usage with click.Command

* :fire: remove bad json 'comma'

* :wrench: fix typeerror 'list' object is not callable in `get_deps_list()`
:wrench: replace datetime.utcnow() -> datetime.now(timezone.utc)

* :wrench: fix bad reference in get_deps_list()

* :wrench: update ci.yml to use pipenv in place of manual venv creation/prep in attempt to resolve `Run .venv/bin/coveralls --service=github` ImportError: cannot import name 'Reporter' from 'coverage.report' error.

* :wrench: add install `pipenv` step to ci.yml

* :wrench: refactor `test_zappa_init` and `cli.py` to allow cleaner mocking of ZappaCLI user inputs.

* Update tests/tests.py

add clear prefix for temporarydirectory

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* :wrench: replace os.path related items with pathlib Path usage
:wrench: change print() to LOG statement

* :wrench: attempt to resolve coveralls error

* :wrench: attempt to migrate to coveralls github action

* :wrench: add carryforward

* :wrench: explicitly set github-token for coverallapp/github-action

* :wrench: turn on coverallsapp/github-action@v2 debug

* :wrench: add --cov-report=xml in Makefile tests command
:wrench: add `format: python` to ci.yml for coveralls

* :wrench: change coveralls format from python -> cobertura

* :wrench: add missing line-feed slash

* :fire: remove commented out "old coveralls support"

---------

Co-authored-by: DS992 <>
Co-authored-by: Gabor Schulz <gabor@gaborschulz.com>
Co-authored-by: shane <shane.cousins@kiconiaworks.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>